// MODULES
export const UPDATE_SELECTED_MODULE = "UPDATE_SELECTED_MODULE";
export const ADD_MODULES = "ADD_MODULES";
export const REPLACE_MODULE = "REPLACE_MODULE";

// TICKETS
export const UPDATE_SELECTED_TICKET = "UPDATE_SELECTED_TICKET";
export const ADD_TICKETS = "ADD_TICKETS";
